// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongestionTax.Infrastructure.Migrations
{
    [DbContext(typeof(TaxDbContext))]
    partial class TaxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("CongestionTax.Domain.CityConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CongestionTax.Domain.RuleSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExemptVehicles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExemptedMonths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxDailyFee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingleChargeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RuleSet");
                });

            modelBuilder.Entity("Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("TaxRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleSetId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId");

                    b.ToTable("TaxRules");
                });

            modelBuilder.Entity("CongestionTax.Domain.CityConfig", b =>
                {
                    b.HasOne("CongestionTax.Domain.RuleSet", "RuleSet")
                        .WithOne()
                        .HasForeignKey("CongestionTax.Domain.CityConfig", "RuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("Holiday", b =>
                {
                    b.HasOne("CongestionTax.Domain.RuleSet", null)
                        .WithMany("Holidays")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxRule", b =>
                {
                    b.HasOne("CongestionTax.Domain.RuleSet", null)
                        .WithMany("TaxRules")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CongestionTax.Domain.RuleSet", b =>
                {
                    b.Navigation("Holidays");

                    b.Navigation("TaxRules");
                });
#pragma warning restore 612, 618
        }
    }
}
